name: finvet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.0
  - streamlit>=1.20.0
  - numpy>=1.20
  - pandas
  - pip:
    - faiss-cpu
    - sentence-transformers
    - requests
    - tqdm
    - scikit-learn
    - torch
    - bert-score
    - transformers
    - asyncio
    - nest-asyncio
    - langchain
    - langchain-community
    - pyarrow>=11.0.0