# .streamlit/secrets.toml
# This file should not be committed to version control
# These are example values - replace with your actual API keys in Streamlit Cloud

# HuggingFace API token
hf_token = "your_huggingface_token_here"

# Google API key with Fact Check API enabled
google_api_key = "your_google_api_key_here"